#! /usr/bin/ruby 
#
# rv, for better camping
#
# chkconfig: - 85 15
# description: Automatically load mongrels for camping apps from configuration files in /etc/rv

# author: Evan Weaver
# url: http://blog.evanweaver.com/articles/2006/12/19/rv-a-tool-for-luxurious-camping
# license: AFL 3.0

require 'yaml'

# you can change these
USER = "httpd"
RUBY = "/usr/bin/ruby"

# best to leave these alone
ACTION = ARGV[0]
PIDFILE = "mongrel.pid"
APP = "rv_harness.rb"
LOG = "/var/log/rv.log"
NULL_STREAM = "< /dev/null 2>&1 > /dev/null"
LOG_STREAM = "< /dev/null 2>&1 >> #{LOG}"

unless File.exist? LOG
  File.open(LOG, "w") {}
end

if %w[start restart stop status].include? ACTION
  Dir.glob "/etc/rv/*.yml" do |f|
    c = YAML.load_file f
    puts "Application #{f}:"

    Dir.chdir c['dir'] do
      pidfile = File.exists?("#{f}.pid") ? "#{f}.pid" : PIDFILE
      pid = File.open(pidfile) {|f| f.readline.chomp } rescue nil
      running = pid ? `ps -p #{pid}`.split("\n")[1] : false
      
      if ACTION =~ /status/
        if running
          puts "  Running."
        elsif pid
          puts "  Has died."
        else
          puts "  Not running."
        end
      end 
      if ACTION =~ /restart|stop/
          if pid 
            if running
              system %[nohup su -c "kill -9 #{pid} #{NULL_STREAM}" #{USER} #{LOG_STREAM}]
              running = nil
              puts "  Stopped."
            else
              puts "  Not running."
            end
            File.delete pidfile            
          else
            puts "  Pid file #{pidfile.inspect} not found (probably not running to begin with)"
          end
      end
      if ACTION =~ /restart|start/
          unless running 
            puts "  Started."
            system %[nohup su -c "#{RUBY} #{APP} #{c['opts'].join ' '} #{NULL_STREAM}" #{USER} #{LOG_STREAM} &]       
          else
            puts "  Already running."
          end
      end

    end
  end
else 
  puts "No action for #{opt.inspect}"
end

